### ISSUE TITLE
why we need to sign the session

### ISSUE THREAD

**Issue by jameslongyoung** [koajs/session#105]
the config has a attribute named signed, why we need to sign the session and  what's the principle of signing the session

**Comment by dead-horse** [comment]
so you can't change the session's value from client side.

**Comment by jameslongyoung** [comment]
why you return two attribute named sessionid and sessionid.sig instead of only returning the sessionid.sig

**Comment by t1bb4r** [comment]
My understanding:

When using the signed option a malicious client can change sessionid, but the server will reject it because the client can't also guess the corresponding sessionid.sig. Brute forcing both keys should be "impossible".
