### ISSUE TITLE
try ... catch does not worker when use session middleware~!

### ISSUE THREAD

**Issue by superbogy** [koajs/session#112]
node 8.9.4

```
app.use(Session({
  key: 'zeff::sess',
  maxAge: 7 * 86400,
  overwrite: true,
  httpOnly: true,
  signed: true,
  rolling: false,
  renew: false,
}, app));

// custom middleware
app.use(async (ctx, next) => {
  try {
    await next();
  } catch (err) {
    console.log(err);
    ctx.status = 500;
    ctx.body = {
      message: 'server error',
    };
    if (ctx.app.env !== 'production') {
      ctx.body.stack = err.stack.split('\r\n');
    }
  }
});
app.use(router.routes());
app.use(router.allowedMethods());
```
It work wrong when i mount session middleware(put it at anywhere)~!

**Comment by sodawy** [comment]
Could you describe more about `work wrong`? If you just remove the session middleware, it `work right`??

---

In your `custom middleware`, you use `try-catch` and not throw the err or bubbling the err. 
So the other middleware may run unexpected, depended the middleware order.

**Comment by superbogy** [comment]
I had found the bug cause by myself. I put a simple test middleware by router.use() without await keyword.
