### ISSUE TITLE
Are parameters `rolling` and `changed` optional when implement an external session store?

### ISSUE THREAD

**Issue by Bin-Huang** [koajs/session#114]
Excuse me. I am writing an external (redis) session store for koa-session, but I miss problem: 

```
- get(key, maxAge, { rolling }): get session object by key
- set(key, sess, maxAge, { rolling, changed }): set session object for key, with a maxAge (in ms)
- destroy(key): destroy session for key

```

I don't understand the meaning about parameters `rolling` and `changed`.  Are they optional ?  Can I just implement like this?:

- get(key, maxAge)
- set(key, sess, maxAge)
- destroy(key)

**Comment by dead-horse** [comment]
these parameters are optional.

**Comment by Bin-Huang** [comment]
thank

**Comment by Bin-Huang** [comment]
There are a simple external **redis** session store: [koa-redis-session](https://github.com/Bin-Huang/koa-redis-session) for `koa-session`. Maybe it is helpful for someone.

**Comment by eilgin** [comment]
You might prefer using [koa2-session-redis](https://github.com/lonord/koa2-session-redis) instead of your solution as it's better maintained.
