### ISSUE TITLE
bug: maxAge:'session' is not work as expected

### ISSUE THREAD

**Issue by valaxy** [koajs/session#133]
**reproduce the problem:**

```js
const Koa = require('koa')
const KoaSesson = require('koa-session')
const app = new Koa()

app.keys = ['a296ac73-192d-4632-a0cc-dba28b821820']

app.use(KoaSesson({
    key: 'some-session-key',
    maxAge: 'session'
}, app))

app.use(async function(ctx) {
    if (ctx.path === '/favicon.ico') return

    let n = ctx.session.views || 0
    ctx.session.views = ++n
    ctx.body = 'Hello Koa' + n
})

app.listen(13001)
```

1. open browser in `http://localhost:13001/` and refresh the page many times
2. delete cookies
3. also open `http://localhost:13001/` and refresh many times
4. close browser and open it again you can see: **the cookie is not erased as expected!**

**Where could the bug come from?**
I doubt that bug may be produced at https://github.com/koajs/session/blob/master/lib/context.js#L293

```js
if (maxAge === 'session') {
    opts.maxAge = undefined; // ← maybe maxAge should not be overridden by undefined
    json._session = true;
}
```

**Comment by linxea** [comment]
how do you close the browser. you need to quit it completely if you are using macbook. Clicking on the close button does not quit the app.

**Comment by s1v7nteen** [comment]
i use the maxAge: 'session'  is not work as expected  too.  i have to set maxAge = 'session' every time, when i want to set session to user.

**Comment by erroric** [comment]
+1

fix from https://github.com/koajs/session/commit/c487944c22056fdd37433bdeab3d665dbd116744 is not working

I have workaround for this behaviour:

```
app.use(KoaSesson({
    key: 'some-session-key',
    maxAge: 'session',
    beforeSave() {
        this.maxAge = 'session';
    },
}, app))
```

beforeSave callback is restored maxAge value correctly, othervise it is replaced with ONE_DAY value

**Comment by whxaxes** [comment]
https://github.com/koajs/session/pull/136  fixed this bug

**Comment by lakca** [comment]
This question has not been fixed yet?
