### ISSUE TITLE
Feature Request: pass ctx on to custom store methods

### ISSUE THREAD

**Issue by lehni** [koajs/session#144]
I have a koa middleware that handles the creation of database transactions before, and their committing / rolling back after the execution of other middlewares. The transaction object is exposed on the `ctx` object that is passed to all middlewares as `ctx.trx`

Since the session itself is also stored in the database, it would be nice if the various custom `store` methods could receive the associated `ctx` object, so this transaction could also be used to tie the session changes into the same transaction.

Some of the store methods already receive a third object argument with various parameters (`changed` and `rolling` so far), could `ctx` be added there as well? And could this argument also be passed to `store.destroy()`?

If this is agreeable, I'd be happy to create a PR for it.

**Comment by ngot** [comment]
If I understand you correctly, you can use `opts.ContextStore` instead of `opts.store`.

ContextStore must be a class which claims three instance methods demonstrated above. new ContextStore(ctx) will be executed on every request.

**Comment by lehni** [comment]
@ngot you're right, that would solve it, thanks!
