### ISSUE TITLE
[fix] uuid version is deprecated

### ISSUE THREAD

**Issue by mlucool** [koajs/session#220]
## Describe the bug
Per npm:
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

## Actual behavior

Uses uuid < 7

## Expected behavior

Has no deprecated dependencies 

## Code to reproduce

npm i koa-session

## Checklist

- [X] I have searched through GitHub issues for similar issues.
- [X] I have completely read through the README and documentation.
- [X] I have tested my code with the latest version of Node.js and this package and confirmed it is still not working.

**Comment by fengmk2** [comment]
closes by 878669ee2c734e3d9902d83f57e21d2113178b79

**Comment by lehni** [comment]
@fengmk2 why not update straight to v9.0.0 which has been released for a while now?

**Comment by fengmk2** [comment]
> @fengmk2 why not update straight to v9.0.0 which has been released for a while now?

uuid v9 drop Node.js 10.x support, koa-session will be upgrade all deps on next major version.
