### ISSUE TITLE
Default cookie name doesn't satisfy RFC6265

### ISSUE THREAD

**Issue by guersam** [koajs/session#28]
The default cookie name [`koa:sess`](https://github.com/koajs/session/blob/master/index.js#L21) contains `:`, which is not a valid token character in accordance with [RFC6265](https://tools.ietf.org/html/rfc6265#section-4.1.1) and [RFC2616](https://tools.ietf.org/html/rfc2616#section-2.2). Although most web browsers and servers allow this, it causes problems in some more strict environment such as [spray](http://spray.io).

Would you consider remaining it? If so, should we take backward compatibility into account?

**Comment by Oursin** [comment]
Hi, any updates on this ?

I'm building a server that communicates with a [Dart](https://github.com/dart-lang/sdk) application, with session handling via cookies. Dart validates the cookie names against the RFC, and thus throws an error while parsing a `koa:sess` cookie.

For now I've simply changed the name manually, but I think it would be great to have a default cookie name that doesn't break the RFC.

**Comment by zacanger** [comment]
@Oursin #197 fixes this.
