### ISSUE TITLE
session regeneration

### ISSUE THREAD

**Issue by zubairhamid** [koajs/session#34]
some method definition is required for reset/regeneration of session. if any please inform.

**Comment by palmtale** [comment]
Why not fix this issue? Could someone give a comment?
cause I found it's easy to do.

**Comment by urugator** [comment]
I also wonder about this. How can I re-create the session? I want to logout current user just before logging in the new one:
```javascript
// if some user is already logged in destroy his session
if (!ctx.session.isNew) {
   ctx.session = null;            
}    
// login
ctx.session.userId = userId;
```
Can't getter create new session automatically if necessary?

I tried to do it like this:
```javascript
ctx.session = null;
await KoaSession(ctx.app).call(this, ctx, next);
```
But it will throw `TypeError: Cannot redefine property: sessionOptions`

**Comment by ethanpollitt** [comment]
Not sure if this has been added, but I can't find a reference in the docs. I also have the same use case of destroying/recreating a session in a single call.

**Comment by lehni** [comment]
With #221 merged, this can be closed now. 🎉
