### ISSUE TITLE
The session is wrong

### ISSUE THREAD

**Issue by Murongyge** [koajs/session#44]
when I test this code:
var session = require('koa-session');
var koa = require('koa');
var app = koa();

app.keys = ['some secret hurr'];
app.use(session(app));

app.use(function *(){
  var n = this.session.views || 0;
  this.session.views = ++n;
  this.body = n + ' views';
})

app.listen(3000);
console.log('listening on port 3000');
------------------------------------
The browser give the first result: 3 views, 5 views,7....
why?

**Comment by coderhaoxin** [comment]
The browser sends another request for `favicon.ico`
