### ISSUE TITLE
Explicitly state in the README that storing data in session is unsafe

### ISSUE THREAD

**Issue by halt-hammerzeit** [koajs/session#50]
``` javascript
    try {
      yield* next;
    } catch (err) {
      throw err;
    } finally {
      commit(this, this._prevjson, this._sess, opts);
    }
```

This code will break under race conditions.
You should state it explicitly in the documentation so that users don't rely on the session store to be consistent.

**Comment by dead-horse** [comment]
onec you want to store something into any storage, this always can be happened.
