### ISSUE TITLE
set option httpOnly dosen't work 

### ISSUE THREAD

**Issue by zhangmengxue** [koajs/session#54]
I was using koa-session.
While I set httpOnly prop like this:

```javascript
var nickName = encodeURIComponent(userData.data.nick),
        empId = encodeURIComponent(userData.data.empid);
    var cookiesOpt = {
        maxAge : 1296000000,
        path : '/',
        httpOnly: false
    };
    this.cookies.set('nick', nickName, cookiesOpt);
    this.cookies.set('empId', empId, cookiesOpt);
```

I want to get all cookies through document.cookie. but the cookies still have http flag.
Did I miss something?

**Comment by zhangmengxue** [comment]
Actually,I need to clear the old cookies. And I think  it ' s not appropriate.
Whatever, I don't have problems now.

**Comment by tomoat** [comment]
I already clear the old cookies, But it still doesn't work
```js
app.use(session({key: 'koa:sess', signed: true, overwrite: true, httpOnly: false}, app))
```
