### ISSUE TITLE
Why modify app

### ISSUE THREAD

**Issue by andreasgruenh** [koajs/session#59]
Hey guys, 
I'm starting a new project soon and currently deciding which libraries I will be using. 
Now I peaked into the source of this repo, and I wondered, why you guys are needing the app for initialization? Other session middlewares are just modifying the ctx object, not the whole app?

**Comment by niftylettuce** [comment]
good point - we can probably just let you pass `ctx` instead of `app`, I took a look in source and don't see why not

**Comment by andreasgruenh** [comment]
Every middleware gets the ctx object on every request as far as I can see. When the session middle ware is the first in the pipeline, it can attach the session object (as it is doing right now as well) and attach setters and getters additionally.

**Comment by dead-horse** [comment]
we define `session` in app.context directly for better performance.

https://github.com/koajs/session/pull/32
