### ISSUE TITLE
should we auto update expired value every time user connect to server?

### ISSUE THREAD

**Issue by piggyman007** [koajs/session#61]
currently expire value is never change until it is expired.

e.g., if maxAge is 3 minutes

if user always interact with server, that user can play within only 3 minutes and need to re-login.

is it better if koa-session auto update exired value and then user does not need to re-login for every 3 minutes?

**Comment by dead-horse** [comment]
maybe we can add a `rolling` option to support this feature

**Comment by piggyman007** [comment]
good idea

**Comment by nickell** [comment]
Would you accept a PR on this? And if so, is there a recommended approach? I forked and added a naive `rolling` option that seems to work well so far.

I put this in the `finally` block of the `session` middleware:

**Comment by dead-horse** [comment]
`options.rolling` is added
