### ISSUE TITLE
session is worked between two different server with the same ip and host

### ISSUE THREAD

**Issue by chaserstrong** [koajs/session#64]
I am using this middleware for my koa project . And during my coding ,i found this session hasn't been destoryed after i closed my server. As i could access the http request in the same web page which i didn't close before.

My config is like : 
var CONFIG = {
  key: 'koa:sess', /** (string) cookie key (default is koa:sess) */
  maxAge: 0, /** (number) maxAge in ms (default is 1 days) */
  overwrite: true, /** (boolean) can overwrite or not (default true) */
  httpOnly: true, /** (boolean) httpOnly or not (default true) */
  signed: true, /** (boolean) signed or not (default true) */
};

And i focus that this module is based on cookie which means it will still be alive even when the server has been closed.  Am i right?

**Comment by dead-horse** [comment]
yes. https://en.wikipedia.org/wiki/HTTP_cookie
