### ISSUE TITLE
Change project description to make it clear external session stores can be used

### ISSUE THREAD

**Issue by natesilva** [koajs/session#72]
We were using a different session module. I never looked at `koa-session` because the description sounds like it only supports cookies (we use Redis). Turns out, it’s easy to plug Redis into `koa-session`.

It would be helpful to edit the project description on Github and `package.json` so dummies like me will give this a try. This is the most-downloaded Koa session middleware and should be the go-to module for all session needs.

**Comment by gugadev** [comment]
Come on guys, two months after and no one reply this? @natesilva is right, you need to provide an example on how redis can be used with this module or if you need to create a store using koa-redis for example. The doc is confusing about this.

**Comment by dead-horse** [comment]
npm description changed. :)

thanks!
