### ISSUE TITLE
Cannot set cookie expires to be 'Session'.

### ISSUE THREAD

**Issue by jgrayauskie** [koajs/session#76]
In Version 4.0.1(we haven't upgraded to node > 7 yet), the maxAge property has to be a number and by default will set the expires of the browser cookie to now + 24 hours. 

![screen shot 2017-05-24 at 2 43 58 pm](https://cloud.githubusercontent.com/assets/3370227/26420002/753e7eec-408f-11e7-9a0d-f668fd7382da.png)

For more secure browser sessions, it would be great to have the cookie expire when the browser is closed. This is not possible currently.

Would like to be able to set expires too:
![screen shot 2017-05-24 at 2 44 43 pm](https://cloud.githubusercontent.com/assets/3370227/26420058/91f61450-408f-11e7-84ea-e8774e88fda8.png)

**Comment by jgrayauskie** [comment]
I created a PR: #77 

Comments or thoughts on how to best define a cookie to be a session cookie is welcome!

**Comment by kylehood** [comment]
For reference https://www.owasp.org/index.php/Session_Management_Cheat_Sheet#Expire_and_Max-Age_Attributes

**Comment by jgrayauskie** [comment]
PR Merged to 4.1.0
