### ISSUE TITLE
Mention Node ^7.6 or ^8 as requirement in Docs

### ISSUE THREAD

**Issue by myyellowshoe** [koajs/session#79]
I recently installed this package, and got some fun errors around async/await in the package:
```
koa-session/index.js:37
  return async function session(ctx, next) {
               ^^^^^^^^
SyntaxError: Unexpected token function
```

Upon to updating to Node 8.10 all is well, and right in the world.
Normally this probaby wouldn't be needed, but since I'm sure alot of folks (like me) are still running a node v6 of some kind, would be handy to mention it.

Created a pull request:
https://github.com/koajs/session/pull/78

**Comment by dead-horse** [comment]
closed via #78
