### ISSUE TITLE
What is the use of app.keys?

### ISSUE THREAD

**Issue by vincent-yao27** [koajs/session#96]
There is no description about ` app.keys` defined in the example. I wonder what's the use of it and if it's a must?

**Comment by dead-horse** [comment]
you should set `app.keys` to sign the cookie, so user can not modify your cookie from browser

**Comment by vincent-yao27** [comment]
thx. 😉 besides, is there any way else to pass the `keys` to `session`. adding a property to `app` feels a bit of strange.

**Comment by vincent-yao27** [comment]
SORRY!! i didn't look up the docs of Koa 😢  it's totally my fault. thank you so much

**Comment by ilaipi** [comment]
it seems koa will pass the `app.keys` to `cookies` lib,
[pillarjs/cookies](https://github.com/pillarjs/cookies)

## pillarjs/cookies
```
cookies = new Cookies( request, response, [ options ] )
```

## koajs/koa
```
# lib/application.js
context.cookies = new Cookies(req, res, {
    keys: this.keys,
    secure: request.secure
});
```

I think this is the truth.
