### ISSUE TITLE
When set maxAge to 'session', error hanppens with external redis store

### ISSUE THREAD

**Issue by zzxzhang** [koajs/session#99]
Set maxAge to 'session'
const sesseionConfig = {
  key: sessionName,
  overwrite: false,
  maxAge: 'session',
  store: redisStore
}

The ttl param will be 'session' and then client.setex will be called with 'session' as the second param which should be a number. So redis client throw an error: 'ERR value is not an integer or out of range'

RedisStore.prototype.set = function *(sid, sess, ttl) {
  if (typeof ttl === 'number') {
    ttl = Math.ceil(ttl / 1000);
  }
  sess = JSON.stringify(sess);
  if (ttl) {
    debug('SETEX %s %s %s', sid, ttl, sess);
    yield this.client.setex(sid, ttl, sess);
  } else {
    debug('SET %s %s', sid, sess);
    yield this.client.set(sid, sess);
  }
  debug('SET %s complete', sid);
};

**Comment by brendtumi** [comment]
[context.js Line 249](https://github.com/koajs/session/blob/master/lib/context.js#L249) TTL parameter will be passed as "undefined" if you set as "session".
If not set at all it will be "ONE_DAY".

Run you code `DEBUG=koa-session:*,koa-redis*` to display logs and make sure.

**Comment by dead-horse** [comment]
please ensure your redis store handle `session` maxAge correctly, maybe you can set to ONE_DAY if maxAge is set to `session`
